# Generated by Django 5.0.6 on 2024-12-17 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas_estudiantes', '0002_remove_mesciclolectivo_habilitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='ciclo_lectivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuotas_estudiantes.ciclolectivo', verbose_name='Ciclo Lectivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='nivel_educativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuotas_estudiantes.niveleducativo'),
        ),
    ]
