# Generated by Django 5.0.6 on 2024-12-17 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_alumnos', '0010_alter_estudiante_sexo_estudiante'),
        ('cuotas_estudiantes', '0003_preinscripcion_aprobada_preinscripcion_ciclo_lectivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preinscripcion',
            options={'verbose_name': 'Preinscripción', 'verbose_name_plural': 'Preinscripciones'},
        ),
        migrations.AlterUniqueTogether(
            name='preinscripcion',
            unique_together={('estudiante', 'ciclo_lectivo')},
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='ciclo_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuotas_estudiantes.ciclolectivo'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preinscripciones', to='administracion_alumnos.estudiante'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='nivel_educativo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuotas_estudiantes.niveleducativo'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='preinscripcion',
            name='aprobada',
        ),
    ]
