# Generated by Django 5.0.6 on 2024-12-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_alumnos', '0002_estadodocumentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='num_legajo_estudiante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
