# Generated by Django 5.0.6 on 2024-12-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_alumnos', '0004_alter_estudiante_apellidos_responsable_otro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='sexo_estudiante',
            field=models.CharField(max_length=100),
        ),
    ]
