# Generated by Django 5.0.6 on 2024-12-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_alumnos', '0005_alter_estudiante_sexo_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='sexo_estudiante',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
    ]
