# Generated by Django 5.0.6 on 2024-12-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_alumnos', '0007_alter_estudiante_autoriza_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='marca_temporal',
            field=models.DateTimeField(max_length=100),
        ),
    ]
