# Generated by Django 5.0.6 on 2024-12-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_alumnos', '0008_alter_estudiante_marca_temporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='marca_temporal',
            field=models.CharField(max_length=100),
        ),
    ]
